# Generated by Django 4.0.4 on 2022-05-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='device_id',
            new_name='device',
        ),
    ]
