# Generated by Django 4.0.5 on 2022-07-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_device_id_timeseries_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='access_token',
        ),
    ]
